[profile.dev]
opt-level = 0

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"


[workspace]
members = [
  "deque-loader",
  "deque-loader-derive",
  "crates/async-graphql-demo",
  "crates/db"
]
