[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
name = "async_graphql_demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.6.1", features = ["macros", "rt-multi-thread"] }
http = "0.2.4"
warp = "0.3.1"
async-graphql = "2.9.2"
async-graphql-warp = "2.9.2"
