[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
edition = "2018"
name = "channel-loader"
version = "0.1.0-beta.2"
description = "A channel based solution designed for efficient data loading"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Bajix/channel-loader-rs/"

[dependencies]
async-trait = "0.1.50"
atomic-take = "1.0.0"
booter = "1.0.0"
flume = "0.10.5"
static_init = "1.0.1"
tokio = { version = "1.5.0", features = ["rt", "sync", "time", "macros", "rt-multi-thread"] }
