[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
name = "db"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.3", features = ["postgres", "chrono", "r2d2"] }
